### ISSUE TITLE
404 error from Github when authorizing HubSpot

### ISSUE THREAD

**Issue by tmuehlherr** [ringcentral/hubspot-embeddable-ringcentral-phone#114]
Hi, I love your tool and for the most part, it worked great. Since today, I am getting asked to authorize with HubSpot pretty much every call over and over again, and when I click the Authorize button I see a 404 error from Github. I did not update or changed any versions or settings. Please help. 
Thomas. 

![image](https://user-images.githubusercontent.com/5608599/50880050-f26e2080-1391-11e9-88e0-6110931ca461.png)

**Comment by zxdong262** [comment]
Hi, I moved to ringcentral, so the old url will not work, please try new release >= 0.1.1, sorry for the inconvenience.

**Comment by tmuehlherr** [comment]
Hi,

Thank you for the quick response. I updated to 0.1.1 although the RingCentral widget still shows 0.2.0 in its version number.
The authorization still does not seem to work properly. The sidebar that shows up now displays a HubSpot page and then Login... and then goes away. A new action then still prompts for Authorization. I am happy to sent the LOG file, but where is it?

Best,
Thomas.

**Comment by zxdong262** [comment]
@tmuehlherr You can open developer tool of chrome, check console log, see if there is any error.

**Comment by zxdong262** [comment]
@tmuehlherr I checked again, in mine it do works.

**Comment by zxdong262** [comment]
@tmuehlherr I created one repo in my account to support older version, if you can not get latest version working, you can try using old version. Should works now.

**Comment by zxdong262** [comment]
Strange, that is something I do not expect, and can not reproduce in my mac and ubuntu. Can you confirm you loaded the right folder? I may release a version this week.

**Comment by tmuehlherr** [comment]
I needed to allow the plugin to talk to all hosts. Then it worked. Thanks.

Thomas Muehlherr
Mobile: (310) 614-2401
Skype: muehlhth

On Jan 13, 2019, at 4:51 PM, ZHAO Xudong <notifications@github.com<mailto:notifications@github.com>> wrote:


Strange, that is something I do not expect, and can not reproduce in my mac and ubuntu. Can you confirm you loaded the right folder? I may release a version this week.

**Comment by LeisureZone** [comment]
I am using a PC and I am having that same issue.  When I originally installed the desktop app (version 0.4.1), it authorized and displayed as an integrated desktop app in HubSpot.  I had the ability to call from HubSpot on my desktop, but my contacts were never synced even though I enabled the 'Auto log calls' option.  That has been the extent of my "integration" features.  It has never automatically logged any calls, showed incoming calls from HubSpot as anything other than the phone number, or gave me access to the contacts activities through the desktop app.

After reading a few threads I saw that there was an updated version (0.4.2) so I tried installing that one as well and it did not work.  I thought it may have been because I still have the older version of the extension active, so I removed it, and deactivated it in HubSpot thinking that when I added the extension again it may re appear in HubSpot but it didn't.  I now have version (0.4.3) on my computer and it still will not authorize or show up in HubSpot under 'Integrations'.  

Please Help, thank you.

**Comment by LeisureZone** [comment]
HERE IS THE MESSAGE:

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus
