### ISSUE TITLE
Call not logged immediately

### ISSUE THREAD

**Issue by AminD006** [ringcentral/hubspot-embeddable-ringcentral-phone#185]
Hi,

When using the addon we are noticing a huge lantency between the moment when the call is placed and when the call is autologged in Hubspot. In average it takes like 15 to 20 minutes to see the call automatically logged. Is it normal ?
This behaviour is happening with 3 different versions of the addon including the latest release.

**Comment by zxdong262** [comment]
Could be a network problem, can you test it in another network?

**Comment by AminD006** [comment]
Will give a try. But the network looks ok : No latency, no jitter, VOiP working well...

**Comment by jrheidkamp** [comment]
We notice this as well.  I have 5 users, and it's so slow, we have to abandon the Labs browser extension and move back to the embedded ringcentral version.   Unfortunately, we lose a lot of functionality doing so.   The embedded older version syncs in near realtime for calls.  However, no SMS/MMS logging.   RC Meeting scheduling is also not nearly as good in the older version.   

Is this beta/developer lab version going to replace the older version?   Or will this be moved over to the embedded version once it is more stable?

**Comment by zxdong262** [comment]
@jrheidkamp If you mean the integration in HubSpot app market, it is a different app from this one, you can check the compare table:

https://github.com/ringcentral/ringcentral-integration-for-hubspot/blob/master/features-compare.md

The integration in HubSpot app market is built on top of HubSpot Calling SDK, some of the limitation is due to HubSpot Calling SDK, such as can not support incoming calls etc.

The call log sync requires the server to sent the call log event, if there is call recording, it requires more time to process the call recording.
