### ISSUE TITLE
aut sync asking for contact after every call

### ISSUE THREAD

**Issue by twasheck** [ringcentral/hubspot-embeddable-ringcentral-phone#241]
After I make a call and RC attempts to sync the call with hubspot I am prompted to select which contact, either myself or the contact I called. This happens after every call.

**Comment by zxdong262** [comment]
Only show selection when multi contacts have caller or callee's number.

You can disable this feature by turn on "Auto sync call/message log to all matched contact(do not show selection)" in settings.

Also you may try remove yourself from HubSpot contact and resync all contacts data:

<img width="1077" alt="Screen Shot 2021-02-24 at 8 38 30 AM" src="https://user-images.githubusercontent.com/1641949/108927755-dca83c00-767b-11eb-8f31-d7890835691f.png">

Let me know if you still having any issues.

**Comment by twasheck** [comment]
apologies, I am having a hard time understanding what you are asking and
how it relates to the image.

**Comment by twasheck** [comment]
In order to log every call, I have to manually select which contact...how
do I "remove myself from HubSpot contact and resync all contacts data:"

**Comment by zxdong262** [comment]
Let's say user call with numberA to numberB, a contact C has numberA, contact D and contact E has numberB, when you hung up call, it will sync call log to contact C, D, E, because they either have caller's number or callee's number, 

also since there are multi contacts to sync calll log to, by default it will ask which one user want to sync to, if user do not want to choose, be OK with sync to C, D, E automaticlly, then user can goto settings of the widget to turn on "Auto sync call/message log to all matched contact(do not show selection)"

if user delete contact C, contact D then follow the image to resync data, then contact C, D will be removed from widget database, then the call log would only sync to contact E, then no need to choose, would also result in auto create call log.

Let me know if this desc works for you.

**Comment by twasheck** [comment]
When I try to manually sync the call this will come up which is normal
[image: sync.png]


Then I have the option to choose the contact, the bottom option being the
client I was trying to get ahold of.

[image: choose.png]

If I select "auto sync call/message log to all matched contact (do not show
selection)"

[image: image.png]

and I log the call it is not logged under the proper contact, it is logged
under my entry in hubspot instead of the contact I called.

[image: log.png]

**Comment by twasheck** [comment]
please advise

**Comment by zxdong262** [comment]
@twasheck Can we have a meeting to check it? If so, please send email to drake.zhao@ringcentral.com, with your available time and timezone.
